# Generated by Django 3.2.12 on 2022-06-10 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import pghistory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pghistory', '0003_auto_20201023_1636'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAggregateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                (
                    'pgh_table',
                    models.CharField(
                        help_text='The table under which the event is stored', max_length=64
                    ),
                ),
                (
                    'pgh_data',
                    pghistory.models.PGHistoryJSONField(help_text='The raw data of the event row'),
                ),
                (
                    'pgh_diff',
                    pghistory.models.PGHistoryJSONField(
                        help_text='The diff between the previous event and the current event'
                    ),
                ),
                ('url', models.TextField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('my_pk', models.UUIDField(primary_key=True, serialize=False)),
                ('int_field', models.IntegerField(db_column='integer_field')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('parent_field', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
                (
                    'fk_field',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UniqueConstraintModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('my_char_field', models.CharField(max_length=32, unique=True)),
                ('my_int_field1', models.IntegerField(db_index=True)),
                ('my_int_field2', models.IntegerField()),
                (
                    'my_one_to_one',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to='tests.custommodel'
                    ),
                ),
            ],
            options={
                'unique_together': {('my_int_field1', 'my_int_field2')},
            },
        ),
        migrations.CreateModel(
            name='UntrackedModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('untracked', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                (
                    'parentmodel_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='tests.parentmodel',
                    ),
                ),
                ('child_field', models.CharField(max_length=64)),
            ],
            bases=('tests.parentmodel',),
        ),
        migrations.CreateModel(
            name='UserGroupsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                (
                    'group',
                    models.ForeignKey(
                        db_constraint=False,
                        db_tablespace='',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        related_query_name='+',
                        to='auth.group',
                    ),
                ),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        db_constraint=False,
                        db_tablespace='',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        related_query_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueConstraintModelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('my_char_field', models.CharField(max_length=32)),
                ('my_int_field1', models.IntegerField()),
                ('my_int_field2', models.IntegerField()),
                ('id', models.IntegerField()),
                (
                    'my_one_to_one',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        related_query_name='+',
                        to='tests.custommodel',
                    ),
                ),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='snapshot',
                        to='tests.uniqueconstraintmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnapshotModelSnapshot',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
                ('id', models.IntegerField()),
                (
                    'fk_field',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        related_query_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='snapshot',
                        to='tests.snapshotmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnapshotModelDtFieldIntFieldEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='dt_field_int_field_snapshot',
                        to='tests.snapshotmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnapshotModelDtFieldEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='dt_field_snapshot',
                        to='tests.snapshotmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentModelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('parent_field', models.CharField(max_length=64)),
                ('id', models.IntegerField()),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='event',
                        to='tests.parentmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoPghObjSnapshot',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
                ('id', models.IntegerField()),
                (
                    'fk_field',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        related_query_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoPghObjEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
                ('id', models.IntegerField()),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventModelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                ('int_field', models.IntegerField()),
                ('id', models.IntegerField()),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='event',
                        to='tests.eventmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomSnapshotModel',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('int_field', models.IntegerField()),
                ('id', models.IntegerField()),
                (
                    'fk_field',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'fk_field2',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        related_query_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='custom_related_name',
                        to='tests.snapshotmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomModelSnapshot',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('my_pk', models.UUIDField(serialize=False)),
                ('int_field', models.IntegerField(db_column='integer_field')),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='snapshot',
                        to='tests.custommodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomModelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('my_pk', models.UUIDField(serialize=False)),
                ('int_field', models.IntegerField(db_column='integer_field')),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='event',
                        to='tests.custommodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomEventModel',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('dt_field', models.DateTimeField()),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='custom_related_name',
                        to='tests.eventmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallChildModel',
            fields=[
                (
                    'childmodel_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='tests.childmodel',
                    ),
                ),
                ('small_child_field', models.CharField(max_length=64)),
            ],
            bases=('tests.childmodel',),
        ),
        migrations.CreateModel(
            name='ChildModelEvent',
            fields=[
                (
                    'parentmodel_ptr',
                    models.ForeignKey(
                        auto_created=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name='+',
                        related_query_name='+',
                        serialize=False,
                        to='tests.parentmodel',
                    ),
                ),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('child_field', models.CharField(max_length=64)),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='childmodel_event',
                        to='tests.childmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallChildModelEvent',
            fields=[
                (
                    'childmodel_ptr',
                    models.ForeignKey(
                        auto_created=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name='+',
                        related_query_name='+',
                        serialize=False,
                        to='tests.childmodel',
                    ),
                ),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('small_child_field', models.CharField(max_length=64)),
                (
                    'pgh_context',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='pghistory.context',
                    ),
                ),
                (
                    'pgh_obj',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='smallchildmodel_event',
                        to='tests.smallchildmodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
