# Generated by Django 3.2.15 on 2022-09-14 03:28
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_auto_20220912_2203"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenormContext",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("int_field", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DenormContextEventNoId",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("pgh_context", models.JSONField(null=True)),
                ("id", models.IntegerField()),
                ("int_field", models.IntegerField()),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event_no_id",
                        to="tests.denormcontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DenormContextEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("pgh_context", models.JSONField(null=True)),
                ("pgh_context_id", models.UUIDField(null=True)),
                ("id", models.IntegerField()),
                ("int_field", models.IntegerField()),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="tests.denormcontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_no_id_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_denormcontexteventnoid" ("id", "int_field", "pgh_context", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."int_field", COALESCE(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE)::JSONB, NULL), NOW(), \'snapshot_no_id\', NEW."id"); RETURN NULL;',
                    hash="f2b3abb322604b8c24c71393f69c65946a589932",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_no_id_insert_f9f15",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_no_id_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."int_field" IS DISTINCT FROM NEW."int_field")',
                    func='INSERT INTO "tests_denormcontexteventnoid" ("id", "int_field", "pgh_context", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."int_field", COALESCE(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE)::JSONB, NULL), NOW(), \'snapshot_no_id\', NEW."id"); RETURN NULL;',
                    hash="1dc4d638319556da5d2e6038d14d2380499e0ed3",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_no_id_update_3c605",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tests_denormcontextevent" ("id", "int_field", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."int_field", COALESCE(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE)::JSONB, NULL), COALESCE(CURRENT_SETTING(\'pghistory.context_id\', TRUE)::UUID, NULL), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="42de41a76f29e796018937fdb119686cbb435191",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_37e9f",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="denormcontext",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."int_field" IS DISTINCT FROM NEW."int_field")',
                    func='INSERT INTO "tests_denormcontextevent" ("id", "int_field", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."int_field", COALESCE(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE)::JSONB, NULL), COALESCE(CURRENT_SETTING(\'pghistory.context_id\', TRUE)::UUID, NULL), NOW(), \'snapshot\', NEW."id"); RETURN NULL;',
                    hash="321cdc3c09da13f1063c2d615eea27f9786a829e",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_ca16a",
                    table="tests_denormcontext",
                    when="AFTER",
                ),
            ),
        ),
    ]
