# Generated by Django 4.2.6 on 2023-10-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0008_uniqueconstraintmodelevent_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommodelevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="tests.custommodel",
            ),
        ),
        migrations.AlterField(
            model_name="denormcontextevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="tests.denormcontext",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodelevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="tests.eventmodel",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotimagefieldevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="tests.snapshotimagefield",
            ),
        ),
    ]
